#!/usr/bin/env bash
# Usage: intent_creator.sh
# This script assumes the intent file is available in /tmp/intent.json
set -euo pipefail

INTENT_JSON="/tmp/intent.json"
mkdir -p "$HOME"/repo; cd "$HOME"/repo

INTENT_DESCRIPTION=$(jq -r '.description // "No description provided"' "$INTENT_JSON")
INTENT_GOAL=$(jq -r '.goal // "No goal provided"' "$INTENT_JSON")
INTENT_SLUG=$(jq -r '.slug // empty' "$INTENT_JSON")
INTENT_BRANCH=$(jq -r '.branch' "$INTENT_JSON")/_

if [ -z "$INTENT_SLUG" ]; then
  INTENT_SLUG=""
fi

# FIXME: thomas - we are just reusing the hosts ssh keys for now
git clone --branch main --single-branch --depth 1 git@github.com:Holon-Agentic-Coder/holon-agentic-coder-ref.git .

# Create intent branch from main
git checkout -B "$INTENT_BRANCH" origin/main

# Append intent to intents.jsonl ledger
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S.%6NZ")
jq -c --arg ts "$TIMESTAMP" '. + {status: "proposed", created_at: $ts}' "$INTENT_JSON" >> app/ledger/intents.jsonl

COMMIT_MSG=$(cat <<EOF
intent: created $INTENT_BRANCH

Description:
$INTENT_DESCRIPTION

Goal:
$INTENT_GOAL

Generated by Holon Intent Agent at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
)

# Commit ledger update
git add app/ledger/intents.jsonl

# Set a generic identity for the Holon Agent
git config --local user.email "intent-agent@holon-agentic-coder.com"
git config --local user.name "Holon Intent Agent"
git commit -m "$COMMIT_MSG"
git push -u origin "$INTENT_BRANCH"

echo "Intent branch '$INTENT_BRANCH' created and intent logged."
